config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :orders

  resources :ebay_categories

  resources :product_to_sells do
    collection do
      get 'refresh'
    end
  end

  resources :ebay_items

  resources :products do
    collection do
      get 'refresh'
    end
  end

  root 'products#index'

  get 'orders/new/:product_id' => 'orders#new'
  get 'products/category/:category_name' => 'products#index'
  get 'products/manufacturers/:manufacturer' => 'products#index'
  get 'products/refresh/:id' => 'products#refresh'
  get 'products/download_images/:id' => 'products#download_images'
  get 'product_to_sells/manufacturers/:manufacturer' => 'product_to_sells#index'

end

app/models/ebay_item.rb
class EbayItem < ActiveRecord::Base
  belongs_to :product
  validates :item_id, uniqueness: true
  acts_as_paranoid
end

app/controllers/ebay_items_controller.rb
class EbayItemsController < ApplicationController
  before_action :set_ebay_item, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!

  # GET /ebay_items
  # GET /ebay_items.json
  def index
    @ebay_items = EbayItem.all
  end

  # GET /ebay_items/1
  # GET /ebay_items/1.json
  def show
  end

  # GET /ebay_items/new
  def new
    @ebay_item = EbayItem.new
  end

  # GET /ebay_items/1/edit
  def edit
  end

  # POST /ebay_items
  # POST /ebay_items.json
  def create
    @ebay_item = EbayItem.new(ebay_item_params)

    respond_to do |format|
      if @ebay_item.save
        format.html { redirect_to @ebay_item, notice: 'Ebay item was successfully created.' }
        format.json { render :show, status: :created, location: @ebay_item }
      else
        format.html { render :new }
        format.json { render json: @ebay_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ebay_items/1
  # PATCH/PUT /ebay_items/1.json
  def update
    respond_to do |format|
      if @ebay_item.update(ebay_item_params)
        format.html { redirect_to @ebay_item, notice: 'Ebay item was successfully updated.' }
        format.json { render :show, status: :ok, location: @ebay_item }
      else
        format.html { render :edit }
        format.json { render json: @ebay_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ebay_items/1
  # DELETE /ebay_items/1.json
  def destroy
    @ebay_item.destroy
    respond_to do |format|
      format.html { redirect_to ebay_items_url, notice: 'Ebay item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ebay_item
      @ebay_item = EbayItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ebay_item_params
      params.require(:ebay_item).permit(:product_id, :item_id, :title, :global_id, :category_name, :gallery_url, :view_item_url, :shipping_service_cost_currency_id, :shipping_service_cost_value, :shipping_type, :handling_time, :current_price_currency_id, :current_price_value, :bid_count, :selling_state, :best_offer_enabled, :buy_it_now_available, :start_time, :end_time, :listing_type, :returns_accepted, :condition_display_name)
    end
end

app/helpers/ebay_items_helper.rb
module EbayItemsHelper
end

app/views/ebay_items/_form.html.haml
= form_for(@ebay_item) do |f|
  - if @ebay_item.errors.any?
    #error_explanation
      %h2
        = pluralize(@ebay_item.errors.count, "error")
        prohibited this ebay_item from being saved:
      %ul
        - @ebay_item.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :product_id
    %br
      = f.text_field :product_id
  .field
    = f.label :item_id
    %br
      = f.number_field :item_id
  .field
    = f.label :title
    %br
      = f.text_field :title
  .field
    = f.label :global_id
    %br
      = f.text_field :global_id
  .field
    = f.label :category_name
    %br
      = f.text_field :category_name
  .field
    = f.label :gallery_url
    %br
      = f.text_field :gallery_url
  .field
    = f.label :view_item_url
    %br
      = f.text_field :view_item_url
  .field
    = f.label :shipping_service_cost_currency_id
    %br
      = f.text_field :shipping_service_cost_currency_id
  .field
    = f.label :shipping_service_cost_value
    %br
      = f.text_field :shipping_service_cost_value
  .field
    = f.label :shipping_type
    %br
      = f.text_field :shipping_type
  .field
    = f.label :handling_time
    %br
      = f.number_field :handling_time
  .field
    = f.label :current_price_currency_id
    %br
      = f.text_field :current_price_currency_id
  .field
    = f.label :current_price_value
    %br
      = f.text_field :current_price_value
  .field
    = f.label :bid_count
    %br
      = f.text_field :bid_count
  .field
    = f.label :selling_state
    %br
      = f.text_field :selling_state
  .field
    = f.label :best_offer_enabled
    %br
      = f.check_box :best_offer_enabled
  .field
    = f.label :buy_it_now_available
    %br
      = f.check_box :buy_it_now_available
  .field
    = f.label :start_time
    %br
      = f.datetime_select :start_time
  .field
    = f.label :end_time
    %br
      = f.datetime_select :end_time
  .field
    = f.label :listing_type
    %br
      = f.text_field :listing_type
  .field
    = f.label :returns_accepted
    %br
      = f.check_box :returns_accepted
  .field
    = f.label :condition_display_name
    %br
      = f.text_field :condition_display_name
  .actions
    = f.submit

app/views/ebay_items/edit.html.haml
%h1 Editing ebay_item
= render 'form'
= link_to 'Show', @ebay_item
|
\#{link_to 'Back', ebay_items_path}

app/views/ebay_items/index.html.haml
%h1 Listing ebay_items
%table
  %thead
    %tr
      %th Product
      %th Item
      %th Title
      %th Global
      %th Category name
      %th Gallery url
      %th View item url
      %th Shipping service cost currency
      %th Shipping service cost value
      %th Shipping type
      %th Handling time
      %th Current price currency
      %th Current price value
      %th Bid count
      %th Selling state
      %th Best offer enabled
      %th Buy it now available
      %th Start time
      %th End time
      %th Listing type
      %th Returns accepted
      %th Condition display name
      %th{:colspan => "3"}
  %tbody
    - @ebay_items.each do |ebay_item|
      %tr
        %td= ebay_item.product
        %td= ebay_item.item_id
        %td= ebay_item.title
        %td= ebay_item.global_id
        %td= ebay_item.category_name
        %td= ebay_item.gallery_url
        %td= ebay_item.view_item_url
        %td= ebay_item.shipping_service_cost_currency_id
        %td= ebay_item.shipping_service_cost_value
        %td= ebay_item.shipping_type
        %td= ebay_item.handling_time
        %td= ebay_item.current_price_currency_id
        %td= ebay_item.current_price_value
        %td= ebay_item.bid_count
        %td= ebay_item.selling_state
        %td= ebay_item.best_offer_enabled
        %td= ebay_item.buy_it_now_available
        %td= ebay_item.start_time
        %td= ebay_item.end_time
        %td= ebay_item.listing_type
        %td= ebay_item.returns_accepted
        %td= ebay_item.condition_display_name
        %td= link_to 'Show', ebay_item
        %td= link_to 'Edit', edit_ebay_item_path(ebay_item)
        %td= link_to 'Destroy', ebay_item, method: :delete, data: { confirm: 'Are you sure?' }
%br
  = link_to 'New Ebay item', new_ebay_item_path

app/views/ebay_items/new.html.haml
%h1 New ebay_item
= render 'form'
= link_to 'Back', ebay_items_path

app/views/ebay_items/show.html.haml
%p#notice= notice
%table.table.table-bordered
  %tr
    %th
      %strong Product:
    %td= link_to @ebay_item.product.title, product_url(@ebay_item.product)
  %tr
    %th
      %strong Item:
    %td= @ebay_item.item_id
  %tr
    %th
      %strong Title:
    %td= @ebay_item.title
  %tr
    %th
      %strong Global:
    %td= @ebay_item.global_id
  %tr
    %th
      %strong Category name:
    %td= @ebay_item.category_name
  %tr
    %th
      %strong Gallery url:
    %td= link_to image_tag(@ebay_item.gallery_url), @ebay_item.gallery_url, "data-lightbox" => @ebay_item.gallery_url
  %tr
    %th
      %strong View item url:
    %td= link_to @ebay_item.view_item_url, @ebay_item.view_item_url
  %tr
    %th
      %strong Shipping service cost currency:
    %td= @ebay_item.shipping_service_cost_currency_id
  %tr
    %th
      %strong Shipping service cost value:
    %td= @ebay_item.shipping_service_cost_value
  %tr
    %th
      %strong Shipping type:
    %td= @ebay_item.shipping_type
  %tr
    %th
      %strong Handling time:
    %td= @ebay_item.handling_time
  %tr
    %th
      %strong Current price currency:
    %td= @ebay_item.current_price_currency_id
  %tr
    %th
      %strong Current price value:
    %td= @ebay_item.current_price_value
  %tr
    %th
      %strong Bid count:
    %td= @ebay_item.bid_count
  %tr
    %th
      %strong Selling state:
    %td= @ebay_item.selling_state
  %tr
    %th
      %strong Best offer enabled:
    %td= @ebay_item.best_offer_enabled
  %tr
    %th
      %strong Buy it now available:
    %td= @ebay_item.buy_it_now_available
  %tr
    %th
      %strong Start time:
    %td= @ebay_item.start_time
  %tr
    %th
      %strong End time:
    %td= @ebay_item.end_time
  %tr
    %th
      %strong Listing type:
    %td= @ebay_item.listing_type
  %tr
    %th
      %strong Returns accepted:
    %td= @ebay_item.returns_accepted
  %tr
    %th
      %strong Condition display name:
    %td= @ebay_item.condition_display_name
= link_to 'Edit', edit_ebay_item_path(@ebay_item), :class => "btn btn-default"
= link_to 'Back', ebay_items_path, :class => "btn btn-default"