config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :orders

  resources :ebay_categories

  resources :product_to_sells do
    collection do
      get 'refresh'
    end
  end

  resources :ebay_items

  resources :products do
    collection do
      get 'refresh'
    end
  end

  root 'products#index'

  get 'orders/new/:product_id' => 'orders#new'
  get 'products/category/:category_name' => 'products#index'
  get 'products/manufacturers/:manufacturer' => 'products#index'
  get 'products/refresh/:id' => 'products#refresh'
  get 'products/download_images/:id' => 'products#download_images'
  get 'product_to_sells/manufacturers/:manufacturer' => 'product_to_sells#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :product
  acts_as_paranoid

  validates :product_id, :price_original, :price_yen, :cost, :shipping_cost, presence: true

  before_save :calculate_profit
  before_save :shipped?

  def calculate_profit
    exchange_rate = open("public/exchange_rate.txt", "r").read.to_i
    self.profit = Product.calculate_profit_on_amazon(self)
  end

  def shipped?
    if self.shipped
      self.shipped_at = Date.today
    else
      self.shipped_at = nil
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :set_options, only: [:new, :create, :edit, :update]
  before_action :set_product, only: [:edit, :update]
  before_filter :set_categories, except: [:show, :delete]
  before_filter :authenticate_user!

  # GET /orders
  # GET /orders.json
  def index
    read_exchange_rate
    @conditions = Array.new

    @conditions << "sold_at BETWEEN '#{Date.new(params[:sold_at]["sold_at(1i)"].to_i, params[:sold_at]["sold_at(2i)"].to_i, 1)}' AND '#{Date.new(params[:sold_at]["sold_at(1i)"].to_i, params[:sold_at]["sold_at(2i)"].to_i, -1)}'" if params[:sold_at]
    @conditions << "price_original >= #{params[:low_price]}" unless params[:low_price].blank?
    @conditions << "price_original <= #{params[:high_price]}" unless params[:high_price].blank?
    @conditions << "products.category = '#{params[:category]}'" unless params[:category].blank?

    if params[:manufacturer]
      @conditions << "products.manufacturer = '#{params[:manufacturer]}'"
    end

    @orders = Order.joins(:product).where(@conditions.join(" AND ")).order("sold_at DESC").all # .page params[:page]
    @sales = @orders.sum(:price_original)
    @average_exchange_rate = (@orders.sum(:price_yen) / @sales).round(2)
    @cost = @orders.sum(:cost)
    @shipping_cost = @orders.sum(:shipping_cost)
    @ebay_cost = @sales * 0.1
    @paypal_cost = (@sales * 0.039 + 0.3 * @orders.size)
    @profit = @orders.sum(:profit)

    @products_hash = Product.where(["id IN (?)", @orders.pluck(:product_id)]).inject(Hash.new) {|h, p| h[p.id] = p; h}
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
    @product = Product.find(params[:product_id]) if params[:product_id]
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_order
    @order = Order.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def order_params
    params.require(:order).permit(:product_id, :locale, :memo, :price_original, :price_yen, :cost, :shipping_cost, :profit, :sold_at, :shipped)
  end

  def set_options
    @product_options = ProductToSell.joins(:product).where("listed IS TRUE").inject(Array.new) {|a, pts| a << [pts.product.title, pts.product_id]; a}
  end

  def set_product
    @product = @order.product
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.haml
= form_for @order do |f|
  - if @order.errors.any?
    #error_explanation
      %h2= "#{pluralize(@order.errors.count, "error")} prohibited this order from being saved:"
      %ul
        - @order.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :product
    - if @product
      = f.select :product_id, options_for_select(@product_options, @product.id), {include_blank: true}, class: "form-control"
    - else
      = f.select :product_id, options_for_select(@product_options), {include_blank: true}, class: "form-control"
  .field
    = f.label :locale
    - if @product
      = f.text_field :locale, value: @product.currency, class: "form-control"
    - else
      = f.text_field :locale, class: "form-control"
  .field
    = f.label :price_original
    - if !@order.price_original && @product
      = f.text_field :price_original, value: @product.price, class: "form-control"
    - else
      = f.text_field :price_original, class: "form-control"
  .field
    = f.label :price_yen
    = f.number_field :price_yen, class: "form-control"
  .field
    = f.label :cost
    = f.number_field :cost, class: "form-control"
  .field
    = f.label :shipping_cost
    - if @order.shipping_cost.blank?
      = f.number_field :shipping_cost, value: @product.shipping_cost, class: "form-control"
    - else
      = f.number_field :shipping_cost, class: "form-control"
  .field
    = f.label :profit
    = f.number_field :profit, class: "form-control"
  .form-inline
    .field
      = f.label :sold_at
      = f.date_select :sold_at, {}, class: "form-control"
    = f.label :shipped
    = f.check_box :shipped, class: "form-control"
  .field
    = f.label :memo
    = f.text_area :memo, class: "form-control"
  .actions
    = f.submit 'Save', class: "btn btn-default"
    = link_to 'Back', orders_path, class: "btn btn-default"

app/views/orders/edit.html.haml
%h1 Editing order

= render 'form'

app/views/orders/index.html.haml
%h1 Listing orders
= form_tag("/orders", method: :get) do
  .form-inline
    .field
      .float-left
        %div
          = label_tag :category
          = select_tag :category, options_for_select(@categories, selected: params[:category]), include_blank: true, class: "form-control"
          - if params[:manufacture]
            = hidden_tag :manufacturer, params[:manufacturer]
      .float-left
        = label_tag :low_price
        = text_field_tag :low_price, params[:low_price], class: "form-control"
        = label_tag :high_price
        = text_field_tag :high_price, params[:high_price], class: "form-control"
      .float-left
        = label_tag :date
        - if params[:sold_at]
          = date_select :sold_at, :sold_at, {default: Date.new(params[:sold_at]["sold_at(1i)"].to_i, params[:sold_at]["sold_at(2i)"].to_i, 1), discard_day: true}, class: "form-control"
        - else
          = date_select :sold_at, :sold_at, {discard_day: true}, class: "form-control"
        = "　　"
      .clear
        .float-left
          %table.profit
            %tr
              %th= label_tag :exchange_rate
              %td= "is #{number_with_delimiter @exchange_rate}円"
              %td= "was #{number_with_delimiter @average_exchange_rate}円"
              %td
            %tr
              %th= label_tag :sales
              %td= number_to_currency @sales, locale: :en
              %td= number_to_currency @sales * @average_exchange_rate
              %td
            %tr
              %th= label_tag :ebay_cost
              %td= number_to_currency @ebay_cost, locale: :en
              %td= number_to_currency @ebay_cost * @average_exchange_rate
              %td= number_to_percentage @ebay_cost / @sales * 100, precision: 1
            %tr
              %th= label_tag :paypal_cost
              %td= number_to_currency @paypal_cost, locale: :en
              %td= number_to_currency @paypal_cost * @average_exchange_rate
              %td= number_to_percentage @paypal_cost / @sales * 100, precision: 1
            %tr
              %th= label_tag :supply_cost
              %td
              %td= number_to_currency @cost
              %td= number_to_percentage @cost / (@sales * @average_exchange_rate) * 100, precision: 1
            %tr
              %th= label_tag :shipping_cost
              %td
              %td= number_to_currency @shipping_cost
              %td= number_to_percentage @shipping_cost / (@sales * @average_exchange_rate) * 100, precision: 1
            %tr
              %th= label_tag :withdraw_cost
              %td
              %td= number_to_currency @sales * 3
              %td= number_to_percentage 3 / @average_exchange_rate * 100, precision: 1
            %tr
              %th= label_tag :profit
              %td
              %td= number_to_currency @profit
              %td= number_to_percentage @profit / (@sales * @average_exchange_rate) * 100, precision: 1
      .float-right.action
        = submit_tag "Search", class: "btn btn-default"
        = link_to 'New Product', new_product_path, class: "btn btn-default"
      -# .float-right= paginate @orders

%table.table.table-condensed.table-striped.products
  %tr
    %th Category
    %th Product
    %th Image
    %th Price Original
    %th Price Yen
    %th Supply Cost
    %th Shipping Cost
    %th Ebay Cost
    %th PayPal Cost
    %th Profit
    %th Sold At
    %th Shipped
    %th Memo
    %th

  - @orders.each do |order|
    %tr
      %td= order.product.category
      %td= link_to @products_hash[order.product_id].title, product_path(@products_hash[order.product_id])
      %td
        = link_to image_tag(@products_hash[order.product_id].image_url1.sub(/.jpg$/, "._SL75_.jpg")), @products_hash[order.product_id].image_url1, "data-lightbox" => @products_hash[order.product_id].image_url1 rescue nil
        -# = link_to image_tag(@products_hash[order.product_id].image_url2.sub(/.jpg$/, "._SL75_.jpg")), @products_hash[order.product_id].image_url2, "data-lightbox" => @products_hash[order.product_id].image_url2 rescue nil
        -# = link_to image_tag(@products_hash[order.product_id].image_url3.sub(/.jpg$/, "._SL75_.jpg")), @products_hash[order.product_id].image_url3, "data-lightbox" => @products_hash[order.product_id].image_url3 rescue nil
        -# = link_to image_tag(@products_hash[order.product_id].image_url4.sub(/.jpg$/, "._SL75_.jpg")), @products_hash[order.product_id].image_url4, "data-lightbox" => @products_hash[order.product_id].image_url4 rescue nil
        -# = link_to image_tag(@products_hash[order.product_id].image_url5.sub(/.jpg$/, "._SL75_.jpg")), @products_hash[order.product_id].image_url5, "data-lightbox" => @products_hash[order.product_id].image_url5 rescue nil
      %td
        - case order.locale
        - when "USD"
          = link_to number_to_currency(order.price_original, locale: :en), order.product.url, target: :blank
        %br
        = surround "@", "円" do
          = (order.price_yen / order.price_original.to_f).round(1)
      %td= number_to_currency order.price_yen
      %td= link_to number_to_currency(order.cost), "#{URI.decode(order.product.url_jp).sub(/\?.+$/, '')}#{AMAZON_ASSOCIATE_JP}", target: :blank rescue nil
      %td
        = number_to_currency order.shipping_cost
        %br
        - if order.product.weight && order.product.weight > 220
          = surround "(", "kg)" do
            = (order.product.weight.to_f / 100 * 0.454).round(2)
        - elsif order.product.weight
          = surround "(", "g)" do
            = (order.product.weight.to_f * 4.54).round(0)
      %td
        = number_to_currency order.price_yen * 0.1
      %td
        = number_to_currency order.price_yen * 0.036 + 40
      %td
        - if order.profit > 0
          = number_to_currency order.profit
          %br
          = surround "(", "%)" do
            = (100 * order.profit/(order.cost + order.shipping_cost + order.price_yen * 0.1).to_f).round(1)
        - else
          %span.red
            = number_to_currency order.profit
      %td= order.sold_at.strftime("%m/%d")
      %td
        - if order.shipped
          = order.shipped_at.strftime("%m/%d")
      %td= order.memo
      %td
        = link_to 'Show', order, class: "btn btn-default btn-sm"
        %br
        = link_to 'Edit', edit_order_path(order), class: "btn btn-default btn-sm"
        %br
        = link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm"
  %tr
    %th Category
    %th Product
    %th Image
    %th Price Original
    %th Price Yen
    %th Supply Cost
    %th Shipping Cost
    %th Ebay Cost
    %th PayPal Cost
    %th Profit
    %th Sold At
    %th Shipped
    %th Memo
    %th

-# .float-right= paginate @orders

= link_to 'New Order', new_order_path, class: "btn btn-default btn-sm"

app/views/orders/new.html.haml
.jumbotron.jumbotron-narrow
  %h2 New order

  = render 'form'

  = link_to 'Back', orders_path, :class => "btn btn-default"

app/views/orders/show.html.haml
%table.table.table-bordered

  %tr
    %th
      %strong Product
    %td
      = link_to @order.product.title, product_path(@order.product)
  %tr
    %th
      %strong Price original
    %td
      - case @order.locale
        - when "USD"
          = number_to_currency @order.price_original, locale: :en
  %tr
    %th
      %strong Price yen
    %td
      = number_to_currency @order.price_yen
  %tr
    %th
      %strong Cost
    %td
      = number_to_currency @order.cost
  %tr
    %th
      %strong Shipping cost
    %td
      = number_to_currency @order.shipping_cost
  %tr
    %th
      %strong Profit
    %td
      - if @order.profit > 0
        = number_to_currency @order.profit
      - else
        %span.red
          = number_to_currency @order.profit
  %tr
    %th
      %strong Sold at
    %td
      = @order.sold_at
  %tr
    %th
      %strong Shipped
    %td
      - if @order.shipped
        = @order.shipped
        %br
        = surround "(", ")" do
          = @order.shipped_at
  %tr
    %th
      %strong Memo
    %td
      = @order.memo

= link_to 'Edit', edit_order_path(@order), class: "btn btn-default"
= link_to 'Back', orders_path, class: "btn btn-default"