config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :orders

  resources :ebay_categories

  resources :product_to_sells do
    collection do
      get 'refresh'
    end
  end

  resources :ebay_items

  resources :products do
    collection do
      get 'refresh'
    end
  end

  root 'products#index'

  get 'orders/new/:product_id' => 'orders#new'
  get 'products/category/:category_name' => 'products#index'
  get 'products/manufacturers/:manufacturer' => 'products#index'
  get 'products/refresh/:id' => 'products#refresh'
  get 'products/download_images/:id' => 'products#download_images'
  get 'product_to_sells/manufacturers/:manufacturer' => 'product_to_sells#index'

end

app/controllers/products_controller.rb
# -*- coding: utf-8 -*-
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :refresh, :download_images]
  before_action :read_exchange_rate
  before_filter :set_locale, only: [:index, :show]
  before_filter :set_categories, except: [:show, :delete]
  before_filter :authenticate_user!, except: [:index, :show]
  after_filter :remember_previous_page, only: :index

  # GET /products
  # GET /products.json
  def index
    @product = Product.new
    @conditions = Array.new
    @orders = Array.new

    # refactoring required
    @conditions << "price >= #{params[:low_price]}" unless params[:low_price].blank?
    @conditions << "price <= #{params[:high_price]}" unless params[:high_price].blank?
    unless params[:category].blank?
      @conditions << "category = '#{params[:category]}'"
      @orders <<  "products.title"
    end

    unless params[:category_name].blank?
      @conditions << "category = '#{params[:category_name]}'"
      @orders <<  "products.title" unless @orders.include?("products.title")
    end

    @orders << "products.created_at DESC" unless @orders.include?("products.title")

    unless params[:profit].blank?
      @conditions << "profit > 0"
      @orders << "profit DESC"
    end
    @conditions << "title LIKE '%#{params[:keyword]}%'" unless params[:keyword].blank?
    @conditions << "price IS NOT NULL"
    @conditions << "cost IS NOT NULL"

    if params[:sales_rank]
      @conditions << "sales_rank IS NOT NULL"
      @orders << "sales_rank ASC"
    end

    if params[:manufacturer]
      @conditions << "manufacturer = '#{params[:manufacturer]}'"
    end

    if params[:image]
      @conditions << "image_url1 IS NOT null"
    end

    if params[:ebay]
      @conditions << "selling_state = 'EndedWithSales'"
      if params[:profit]
        @conditions << "profit_ebay > 0"
        @products = Product.joins(:ebay_items).where(@conditions.join(" AND ")).uniq.order(@orders.join(",")).page params[:page]
      else
        @products = Product.joins(:ebay_items).where(@conditions.join(" AND ")).uniq.order(@orders.join(",")).page params[:page]
      end
    else
      @products = Product.where(@conditions.join(" AND ")).order(@orders.join(",")).page params[:page]
    end
    @count = @products.total_count

    # @amazon_profit_hash = @products.inject(Hash.new) {|h, p| h[p.id] = Product.calculate_profit_on_amazon(p) if p.price && p.cost; h}
    @product_to_sells = ProductToSell.where(["product_id in (?)", @products.pluck(:id)]).pluck(:product_id)

    set_ebay_data_for_multiple_products(@products.pluck(:id))
    # @ebay_profit_hash = @products.inject(Hash.new) {|h, p| h[p.id] = Product.calculate_profit_on_ebay(p, @average_hash[p.id]) if !@sold_item_hash[p.id].blank?  && p.cost; h}

    if params[:category_name]
      @form_path = "#{products_path}/category/#{params[:category_name]}"
      @keyword = params[:category_name]
      @description = "#{params[:category_name]}の販売価格"
    else
      @form_path = products_path
    end

    @latest_product = Product.order("updated_at").last

    respond_to do |format|
      format.html # index.html.erb
      format.js # index.js.erb
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @keyword = @product.title
    @description = "#{@product.title}の販売価格"

    # if @product.price && @product.cost
    #   @amazon_profit = Product.calculate_profit_on_amazon(@product)
    # end

    set_ebay_data_for_single_product(@product.id)
    if @average && @product.cost
      # @ebay_profit = Product.calculate_profit_on_ebay(@product, @average)
    end

    @related_products = Product.where(["category = ? AND id != ? AND RAND() < ?", @product.category, @product.id, 0.01]).limit(3)
    # @amazon_profit_hash = @related_products.inject(Hash.new) {|h, p| h[p.id] = Product.calculate_profit_on_amazon(p) if p.price && p.cost; h}

    # puts @related_products.pluck(:id)

    set_ebay_data_for_multiple_products(@related_products.pluck(:id))
    # @ebay_profit_hash = @related_products.inject(Hash.new) {|h, p| h[p.id] = Product.calculate_profit_on_ebay(p, @average_hash[p.id]) if @average_hash[p.id] > 0 && p.cost; h}

    @product_to_sells = ProductToSell.where(["product_id = ?", @product.id]).pluck(:product_id)
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        find_ebay_completed_items(@product.title, @product.id)

        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /products/refresh/1
  # GET /products/refresh/1.json
  def refresh
    Product.lookup @product.asin
    redirect_to product_path @product
  end

  def download_images
    @destination = "#{Etc.getpwuid.dir}/Downloads/amazon"
    unless File.exists?(@destination)
      unless File.exists?("#{Etc.getpwuid.dir}/Downloads")
        Dir.mkdir "#{Etc.getpwuid.dir}/Downloads"
      end
      Dir.mkdir @destination
    end

    [@product.image_url1, @product.image_url2, @product.image_url3, @product.image_url4, @product.image_url5].each_with_index do |url, i|
      unless url.blank?
        /.+\.([a-z]+)$/ =~ url
        extention = $1
        get_content(url, @product.title, "#{i}.#{extention}")
      end
    end

    render nothing: true
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:asin, :category, :manufacturer, :model, :title, :color, :size, :weight, :features, :sales_rank, :url, :url_jp, :image_url1, :image_url2, :image_url3, :image_url4, :image_url5, :currency, :price, :cost, :shipping_cost, :profit, :profit_ebay, :ebay_average, :deleted_at)
  end

  def remember_previous_page
    session[:previous_page] = request.env['HTTP_REFERER'] || products_url
  end

  def get_content(uri, title, file_name)
    hc = HTTPClient.new
    begin
      content = hc.get_content(uri, :get, {})
    rescue
    end

    if content.nil? || content.size < 10
      p "file not found from #{uri}."
      return false
    else
      destination = "#{@destination}/#{title.gsub('/', ' ')}"
      unless File.exists?(destination)
        Dir.mkdir destination
      end

      if File.exists?("#{destination}/#{file_name}")
        p "#{file_name} already exists."
        return
      end

      File.open("#{destination}/#{file_name}", "wb") do |f|
        f.print content
        p "#{file_name} saved from #{uri}."
      end
    end
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.haml
= form_for @product do |f|
  .field
    = label_tag :search
    %br
      = text_field_tag :search, "Japan Import", :class => "form-control"
  .actions
    = f.submit "Search", :class => "btn btn-default"

= form_for(@product) do |f|
  - if @product.errors.any?
    #error_explanation
      %h2
        = pluralize(@product.errors.count, "error")
        prohibited this product from being saved:
      %ul
        - @product.errors.full_messages.each do |message|
          %li= message
  .field
    = f.label :asin
    %br
      = f.text_field :asin, :class => "form-control"
  .field
    = f.label :category
    %br
    - if @product.category
      = f.select :category, options_for_select(@categories, @product.category), {}, :class => "form-control"
    - else
      = f.select :category, options_for_select(@categories), {}, :class => "form-control"
  .field
    = f.label :manufacturer
    %br
      = f.text_field :manufacturer, :class => "form-control"
  .field
    = f.label :model
    %br
      = f.text_field :model, :class => "form-control"
  .field
    = f.label :title
    %br
      = f.text_field :title, :class => "form-control"
  .field
    = f.label :color
    %br
      = f.text_field :color, :class => "form-control"
  .field
    = f.label :size
    %br
      = f.text_field :size, :class => "form-control"
  .field
    = f.label :weight
    %br
      = f.text_field :weight, :class => "form-control"
  .field
    = f.label :features
    %br
      = f.text_field :features, :class => "form-control"
  .field
    = f.label :sales_rank
    %br
      = f.number_field :sales_rank, :class => "form-control"
  .field
    = f.label :url
    %br
      = f.text_field :url, :class => "form-control"
  .field
    = f.label :url_jp
    %br
      = f.text_field :url_jp, :class => "form-control"
  .field
    = f.label :image_url1
    %br
      = f.text_field :image_url1, :class => "form-control"
  .field
    = f.label :image_url2
    %br
      = f.text_field :image_url2, :class => "form-control"
  .field
    = f.label :image_url3
    %br
      = f.text_field :image_url3, :class => "form-control"
  .field
    = f.label :image_url4
    %br
      = f.text_field :image_url4, :class => "form-control"
  .field
    = f.label :image_url5
    %br
      = f.text_field :image_url5, :class => "form-control"
  .field
    = f.label :currency
    %br
      = f.text_field :currency, :class => "form-control"
  .field
    = f.label :price
    %br
      = f.text_field :price, :class => "form-control"
  .field
    = f.label :cost
    %br
      = f.number_field :cost, :class => "form-control"
  .field
    = f.label :shipping_cost
    %br
      = f.number_field :shipping_cost, :class => "form-control"
  .actions
    = f.submit :class => "btn btn-default"

app/views/products/_product.html.haml
.col-lg-4.col-sm-6.product
  - if product.image_url5
    = link_to image_tag(product.image_url5.sub(/.jpg$/, "._SL120_.jpg"), alt: product.title, class: "img-circle img-responsive img-center"), product.image_url5, "data-lightbox" => product.image_url5, "data-title" => product.title
  - elsif product.image_url4
    = link_to image_tag(product.image_url4.sub(/.jpg$/, "._SL120_.jpg"), alt: product.title, class: "img-circle img-responsive img-center"), product.image_url4, "data-lightbox" => product.image_url4, "data-title" => product.title
  - elsif product.image_url3
    = link_to image_tag(product.image_url3.sub(/.jpg$/, "._SL120_.jpg"), alt: product.title, class: "img-circle img-responsive img-center"), product.image_url3, "data-lightbox" => product.image_url3, "data-title" => product.title
  - elsif product.image_url2
    = link_to image_tag(product.image_url2.sub(/.jpg$/, "._SL120_.jpg"), alt: product.title, class: "img-circle img-responsive img-center"), product.image_url2, "data-lightbox" => product.image_url2, "data-title" => product.title
  - elsif product.image_url1
    = link_to image_tag(product.image_url1.sub(/.jpg$/, "._SL120_.jpg"), alt: product.title, class: "img-circle img-responsive img-center"), product.image_url1, "data-lightbox" => product.image_url1, "data-title" => product.title
  - else
    = image_tag("/missing_120.png", alt: "No large image: #{product.title}", class: "img-circle img-responsive img-center")
  %ul
    %li
      %h2.item-h2= link_to product.title, product
    %li
      %h3.item-h3{data:{no_turbolink: true}}= link_to product.category, "#{products_path}/category/#{product.category}"
    %li
      %h4.item-h4
        %p
        = "US #{number_to_currency product.price, locale: :en}"
        - if product.price
          %small= "#{number_to_currency product.price * @exchange_rate}@#{number_to_currency @exchange_rate, locale: :en}"
        %p
        = "JP #{number_to_currency(product.cost)}"

    %li
      %h5= "#{t('activerecord.attributes.product.shipping_cost')}: #{number_to_currency product.shipping_cost}〜 (#{(product.weight.to_f / 100 * 0.454).round(2)}kg)"

    %li
      %h5= "#{t('views.product.minimum_price')}: #{number_to_currency(Product.minimum_price(product), locale: :en)}"

    - if product.profit || product.profit_ebay
      %li.profit
        = "#{t('activerecord.attributes.product.profit')}:"
        - if product.profit
          %h4
            %small amazon
            - if product.profit/product.cost.to_f >= 0.1
              %span.green
                = number_to_currency product.profit
                = "(#{number_to_percentage(100*product.profit/product.cost, precision: 1)})"
            - elsif product.profit < 0
              %span.red
                = number_to_currency product.profit
            - else
              = number_to_currency product.profit
              = "(#{number_to_percentage(100*product.profit/product.cost, precision: 1)})"

        - if product.profit_ebay
          %h4
            %small ebay
            - if product.profit_ebay/product.cost.to_f >= 0.1
              %span.green
                = number_to_currency product.profit_ebay
                = "(#{number_to_percentage(100*product.profit_ebay/product.cost, precision: 1)})"
            - elsif product.profit_ebay < 0
              %span.red
                = number_to_currency product.profit_ebay
            - else
              = number_to_currency product.profit_ebay
              = "(#{number_to_percentage(100*product.profit_ebay/product.cost, precision: 1)})"
          %h4
            %small= "#{t('views.product.sold_count')}: #{@sold_item_hash[product.id].count}"
            %small
              = "#{t('views.product.average')}: "
              = link_to number_to_currency(@average_hash[product.id], locale: :en), "http://rover.ebay.com/rover/1/711-53200-19255-0/1?icep_ff3=9&pub=5575129667&toolid=10001&campid=5337713314&customid=&icep_uq=#{URI.escape(product.title)}&LH_Complete=1&LH_Sold=1&icep_sellerId=&icep_ex_kw=&icep_sortBy=12&icep_catId=&icep_minPrice=&icep_maxPrice=&ipn=psmain&icep_vectorid=229466&kwid=902099&mtid=824&kw=lg", target: :blank

          %h4
            %small
              = "#{t('views.product.sales_rank')}: "
              = number_with_delimiter product.sales_rank

    %li
      - if product.price
        = link_to "Amazon US", product.url, class: "btn btn-default btn-sm", target: :blank
      - if product.cost
        = link_to "Amazon JP", product.url_jp, class: "btn btn-default btn-sm", target: :blank
      = link_to "ebay US", "http://rover.ebay.com/rover/1/711-53200-19255-0/1?icep_ff3=9&pub=5575129667&toolid=10001&campid=5337713314&customid=&icep_uq=#{URI.escape(product.title)}&icep_sellerId=&icep_ex_kw=&icep_sortBy=12&icep_catId=&icep_minPrice=&icep_maxPrice=&ipn=psmain&icep_vectorid=229466&kwid=902099&mtid=824&kw=lg", class: "btn btn-default btn-sm", target: :blank

      - if user_signed_in?
        - if @product_to_sells.include? product.id
          %span.btn.btn-info Added
        - else
          = link_to 'Add', product_to_sells_path, method: "post", data: { confirm: 'Are you sure?', params: { product_to_sell: { product_id: product.id } } }, remote: true, class: "btn btn-success btn-sm"

app/views/products/_related_product.html.haml
.col-sm-3.col-xs-6.product
  - if product.image_url1
    = link_to image_tag(product.image_url1.sub(/.jpg$/, "._SL120_.jpg"), class: "img-responsive portfolio-product"), product.image_url1, "data-lightbox" => product.image_url1, "data-title" => product.title
  - else
    = image_tag "/missing_120.png", alt: "No Image", class: "img-responsive portfolio-product"
  %ul
    %li= link_to product.title, product
    %li
      %h5{data:{no_turbolink: true}}= link_to product.category, "#{products_path}/category/#{product.category}"

    %li= "#{t('activerecord.attributes.product.price')}:"
    %li
      %h4
        %p
        = "US #{number_to_currency product.price, locale: :en}"
        - if product.price
          %small= "#{number_to_currency product.price * @exchange_rate}@#{number_to_currency @exchange_rate, locale: :en}"
        %p
        = "JP #{number_to_currency(product.cost)}"

      %li
        %h5= "#{t('activerecord.attributes.product.shipping_cost')}: #{number_to_currency product.shipping_cost}〜"

      %li
        %h5= "#{t('views.product.minimum_price')}: #{number_to_currency(Product.minimum_price(product), locale: :en)}"

      - if product.profit || product.profit_ebay
        %li.profit
          = "#{t('activerecord.attributes.product.profit')}:"
          - if product.profit
            %h4
              %small amazon
              - if product.profit/product.cost.to_f >= 0.1
                %span.green
                  = number_to_currency product.profit
                  = "(#{number_to_percentage(100*product.profit/product.cost, precision: 1)})"
              - elsif product.profit < 0
                %span.red
                  = number_to_currency product.profit
              - else
                = number_to_currency product.profit
                = "(#{number_to_percentage(100*product.profit/product.cost, precision: 1)}%)"

          - if product.profit_ebay
            %h4
              %small ebay
              - if product.profit_ebay/product.cost.to_f >= 0.1
                %span.green
                  = number_to_currency product.profit_ebay
                  = "(#{number_to_percentage(100*product.profit_ebay/product.cost, precision: 1)}%)"
              - elsif product.profit_ebay < 0
                %span.red
                  = number_to_currency product.profit_ebay
              - else
                = number_to_currency product.profit_ebay
                = "(#{number_to_percentage(100*product.profit_ebay/product.cost, precision: 1)}%)"
            = "#{t('views.product.sold_count')}: #{@sold_item_hash[product.id].count}"

      %li
        - if product.price
          = link_to "Amazon US", product.url, class: "btn btn-default btn-sm", target: :blank
        - if product.cost
          = link_to "Amazon JP", product.url_jp, class: "btn btn-default btn-sm", target: :blank
        = link_to "ebay US", "http://rover.ebay.com/rover/1/711-53200-19255-0/1?icep_ff3=9&pub=5575129667&toolid=10001&campid=5337713314&customid=&icep_uq=#{URI.escape(product.title)}&icep_sellerId=&icep_ex_kw=&icep_sortBy=12&icep_catId=&icep_minPrice=&icep_maxPrice=&ipn=psmain&icep_vectorid=229466&kwid=902099&mtid=824&kw=lg", class: "btn btn-default btn-sm", target: :blank
  / /.row

app/views/products/edit.html.haml
.jumbotron.jumbotron-narrow
  %h2 Editing product
  = render 'form'
  = link_to 'Show', @product, class: "btn btn-default"
  = link_to 'Back', product_path(@product), class:  "btn btn-default"

app/views/products/index.js.haml
$("#count").hide().html("#{number_with_delimiter @count}").fadeIn();
$("#products").hide().html("#{escape_javascript(render @products)}").fadeIn();
$("div.pagination").hide().html("#{escape_javascript(paginate(@products, :remote => true).to_s)}").fadeIn();

NProgress.done();

app/views/products/new.html.haml
.jumbotron.jumbotron-narrow
  %h2 New product
  = render 'form'
  = link_to 'Back', products_path, :class => "btn btn-default"

app/views/products/show.html.haml
.container.mt90.show
  .row
    .col-lg-12
      %h1.page-header
        %strong
          = link_to @product.title, "#{products_path}?keyword=#{@product.title}"
        %br
        %h2
          %small= link_to @product.category, "#{products_path}/category/#{@product.category}"
  / /.row
  / Portfolio Product Row
  .row
    .col-md-8.item-img
      - if @product.image_url5
        = image_tag @product.image_url5, class: "img-responsive"
      - elsif @product.image_url4
        = image_tag @product.image_url4, class: "img-responsive"
      - elsif @product.image_url3
        = image_tag @product.image_url3, class: "img-responsive"
      - elsif @product.image_url2
        = image_tag @product.image_url2, class: "img-responsive"
      - elsif @product.image_url1
        = image_tag @product.image_url1, class: "img-responsive"

      = link_to image_tag(@product.image_url1.sub(/.jpg$/, "._SL120_.jpg")), @product.image_url1, "data-lightbox" => @product.image_url1 rescue nil
      = link_to image_tag(@product.image_url2.sub(/.jpg$/, "._SL120_.jpg")), @product.image_url2, "data-lightbox" => @product.image_url2 rescue nil
      = link_to image_tag(@product.image_url3.sub(/.jpg$/, "._SL120_.jpg")), @product.image_url3, "data-lightbox" => @product.image_url3 rescue nil
      = link_to image_tag(@product.image_url4.sub(/.jpg$/, "._SL120_.jpg")), @product.image_url4, "data-lightbox" => @product.image_url4 rescue nil
      = link_to image_tag(@product.image_url5.sub(/.jpg$/, "._SL120_.jpg")), @product.image_url5, "data-lightbox" => @product.image_url5 rescue nil

      .clear.download
        = link_to t("links.product.download_images"), "#{products_path}/download_images/#{@product.id}", remote: true, class: "btn btn-default"

    .col-md-4
      %h3 商品詳細
      %ul
        %li
          %h4
            = "#{t('activerecord.attributes.product.price')}:"
            %p
            = "US #{number_to_currency @product.price, locale: :en}"
            - if @product.price
              %small= "#{number_to_currency @product.price * @exchange_rate}@#{number_to_currency @exchange_rate, locale: :en}"
            %p
            = "JP #{number_to_currency(@product.cost)}"
        %li
          %h5= "#{t('activerecord.attributes.product.shipping_cost')}: #{number_to_currency @product.shipping_cost}〜"

        %li.profit
          = "#{t('activerecord.attributes.product.profit')}:"
          - if @product.profit && @product.cost
            %h4
              %small amazon
              - if @product.profit/@product.cost.to_f >= 0.1
                %span.green
                  = number_to_currency @product.profit
                  = "(#{number_to_percentage(100*@product.profit/@product.cost, precision: 1)})"
              - elsif @product.profit < 0
                %span.red
                  = number_to_currency @product.profit
              - else
                = number_to_currency @product.profit
                = "(#{number_to_percentage(100*@product.profit/@product.cost, precision: 1)})"
          - if @product.cost && @ebay_profit
            %h4
              %small ebay
              - if @ebay_profit.to_f > 0.2
                %span.green
                  = number_to_currency @ebay_profit
                  = "(#{number_to_percentage(100*@ebay_profit/@product.cost, precision: 1)})"
              - elsif @ebay_profit < 0
                %span.red
                  = number_to_currency @ebay_profit
              - else
                = number_to_currency @ebay_profit
                = "(#{number_to_percentage(100*@ebay_profit/@product.cost, precision: 1)})"

        %li= "#{t('activerecord.attributes.product.asin')}: #{@product.asin}"
        %li
          = "#{t('activerecord.attributes.product.manufacturer')}: "
          - if @product.manufacturer
            = link_to @product.manufacturer, "/products/manufacturers/#{@product.manufacturer}"
        %li= "#{t('activerecord.attributes.product.model')}: #{@product.model}"
        %li= "#{t('activerecord.attributes.product.color')}: #{@product.color}"
        %li= "#{t('activerecord.attributes.product.size')}: #{@product.size}"
        %li= "#{t('activerecord.attributes.product.weight')}: #{(@product.weight.to_f / 100 * 0.454).round(2)}kg"
        %li= "#{t('activerecord.attributes.product.features')}: #{@product.features}"
        %li= "#{t('activerecord.attributes.product.sales_rank')}: #{number_with_delimiter @product.sales_rank}"

      - if @product.price
        = link_to "Amazon US", @product.url, class: "btn btn-default", target: :blank
      - if @product.cost
        = link_to "Amazon JP", @product.url_jp, class: "btn btn-default", target: :blank
        = link_to "ebay US", "http://rover.ebay.com/rover/1/711-53200-19255-0/1?icep_ff3=9&pub=5575129667&toolid=10001&campid=5337713314&customid=&icep_uq=#{URI.escape(@product.title)}&icep_sellerId=&icep_ex_kw=&icep_sortBy=12&icep_catId=&icep_minPrice=&icep_maxPrice=&ipn=psmain&icep_vectorid=229466&kwid=902099&mtid=824&kw=lg", class: "btn btn-default", target: :blank
        = image_tag "http://rover.ebay.com/roverimp/1/711-53200-19255-0/1?ff3=4&pub=5575129667&toolid=10001&campid=5337712152&customid=&mpt=[CACHEBUSTER]", style: "text-decoration:none;border:0;padding:0;margin:0;"
      - if user_signed_in?
        - if @product_to_sells.include? @product.id
          %span.btn.btn-info Added
        - else
          = link_to 'Add', product_to_sells_path, method: "post", data: { confirm: 'Are you sure?', params: { product_to_sell: { product_id: @product.id } } }, remote: true, class: "btn btn-success btn-sm"

          = link_to 'Edit', edit_product_path(@product), :class => "btn btn-default"
          = link_to 'Refresh', "#{refresh_products_path}/#{@product.id}", :class => "btn btn-default"
          = link_to 'Destroy', @product, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger"

  / /.row
  .row
    .col-lg-12
      %h3.page-header= t("activerecord.models.ebay_item")
      %ul
        %li
          = t("views.product.all_count")
          = @ebay_items.count
          %br
          = t("views.product.sold_count")
          = number_with_delimiter @sold_items.count
          - if @average
            %br
            = t("views.product.average")
            = "#{@locale} #{number_with_delimiter @average}"
        %li
          - @ebay_items.each do |item|
            %li
              = link_to item.title, "http://rover.ebay.com/rover/1/711-53200-19255-0/1?icep_ff3=2&pub=5575129667&toolid=10001&campid=5337714063&customid=&icep_item=#{item.item_id}&ipn=psmain&icep_vectorid=229466&kwid=902099&mtid=824&kw=lg", target: :blank
              - if item.selling_state == "EndedWithSales"
                %b.green= item.selling_state
              - elsif item.selling_state == "EndedWithoutSales"
                %span.red= item.selling_state
              = link_to "(#{item.current_price_currency_id} #{item.current_price_value}@#{item.end_time.strftime('%Y/%m/%d')})", item.view_item_url
        %p.right
          = link_to t("links.product.more"), "http://rover.ebay.com/rover/1/711-53200-19255-0/1?icep_ff3=9&pub=5575129667&toolid=10001&campid=5337713314&customid=&icep_uq=#{URI.escape(@product.title)}&LH_Complete=1&LH_Sold=1&icep_sellerId=&icep_ex_kw=&icep_sortBy=12&icep_catId=&icep_minPrice=&icep_maxPrice=&ipn=psmain&icep_vectorid=229466&kwid=902099&mtid=824&kw=lg", class: "btn btn-default", target: :blank

  / Related Projects Row
  .row
    .col-lg-12
      %h3.page-header 関連商品
      = render @related_products

  .row
    .col-lg-12.page-header{data:{no_turbolink: true}}= link_to t("links.back"), :back, class: "btn btn-default"