config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :orders

  resources :ebay_categories

  resources :product_to_sells do
    collection do
      get 'refresh'
    end
  end

  resources :ebay_items

  resources :products do
    collection do
      get 'refresh'
    end
  end

  root 'products#index'

  get 'orders/new/:product_id' => 'orders#new'
  get 'products/category/:category_name' => 'products#index'
  get 'products/manufacturers/:manufacturer' => 'products#index'
  get 'products/refresh/:id' => 'products#refresh'
  get 'products/download_images/:id' => 'products#download_images'
  get 'product_to_sells/manufacturers/:manufacturer' => 'product_to_sells#index'

end

app/models/product_to_sell.rb
class ProductToSell < ActiveRecord::Base
  belongs_to :product
  validates :product_id, uniqueness: true
  acts_as_paranoid
end

app/controllers/product_to_sells_controller.rb
require 'csv'

class ProductToSellsController < ApplicationController
  before_action :set_product_to_sell, only: [:show, :edit, :update, :destroy]
  before_action :read_exchange_rate
  after_action :list_to_ebay, only: :update
  before_filter :set_locale, only: [:index]
  before_filter :authenticate_user!
  after_filter :remember_previous_page, only: :index

  # @@app_id = "Chishaku-8e8f-48de-a23a-e1304518388d" # sandbox
  @@app_id = "Chishaku-0efe-4739-a2ff-dba4724f0514" # production

  @@return_accespted_option = "ReturnsAccepted"
  @@refund_option = "MoneyBack"
  @@returns_within_option = "Days_30"
  @@refund_description = "If for any reason you are not satisfied with your order, simply send it back to us. You are responsible for return shipping. Once your return is processed, you will receive a refund for the amount paid for the returned item back to the original method of payment. Any outbound shipping charges paid will not be refunded if the order is returned. All merchandise must be the same condition it was received."

  # GET /product_to_sells
  # GET /product_to_sells.json
  def index
    set_categories

    @conditions = Array.new
    @orders = Array.new

    @conditions << "price >= #{params[:low_price]}" unless params[:low_price].blank?
    @conditions << "price <= #{params[:high_price]}" unless params[:high_price].blank?
    @conditions << "category = '#{params[:category]}'" unless params[:category].blank?
    @conditions << "listed = TRUE" if params[:listed] == "1"
    @conditions << "listed IS NOT TRUE" if params[:unlisted] == "1"

    if params[:sales_rank]
      @conditions << "sales_rank IS NOT NULL"
      @orders << "sales_rank ASC"
    end

    if params[:manufacturer]
      @conditions << "manufacturer = '#{params[:manufacturer]}'"
    end

    @orders = Array.new
    @orders << "products.category"
    @orders << "product_to_sells.created_at DESC"

    @product_to_sells = ProductToSell.joins(:product).where(@conditions.join(" AND ")).order(@orders.join(", ")).page params[:page]

    @profit_hash = Product.where(["id IN (?)", @product_to_sells.pluck(:product_id)]).inject(Hash.new(nil)) {|h, p|
      h[p.id] = (p.price * (1 - 0.1 - 0.039) - 0.3) * @exchange_rate - p.shipping_cost - p.cost if p.price && p.cost; h
    }

    set_ebay_data_for_multiple_products(@product_to_sells.pluck(:product_id))
  end

  # GET /product_to_sells/1
  # GET /product_to_sells/1.json
  def show
    @profit = Product.calculate_cost(@product_to_sell.product_id) if @product_to_sell.product.price && @product_to_sell.product.shipping_cost && @product_to_sell.product.cost
    set_ebay_data_for_single_product(@product_to_sell.product.id)
    @ebay_profit = (@average * (1 - 0.1 - 0.039) - 0.3)*@exchange_rate - @product_to_sell.product.cost - @product_to_sell.product.shipping_cost if @average && @product_to_sell.product.cost && @product_to_sell.product.shipping_cost
  end

  # GET /product_to_sells/new
  def new
    @product_to_sell = ProductToSell.new
  end

  # GET /product_to_sells/1/edit
  def edit
    set_ebay_data_for_single_product(@product_to_sell.product.id)

    @start_price = (@product_to_sell.product.cost / @exchange_rate) * 1.3.ceil
    if @start_price > @product_to_sell.product.price
      @start_price = (@product_to_sell.product.price * 0.97).round(1)
    end

    @start_price = @average if @average && @average > @start_price
  end

  # POST /product_to_sells
  # POST /product_to_sells.json
  def create
    @product_to_sell = ProductToSell.new(product_to_sell_params)
    @product_to_sell.category_id = EbayCategory.where(["category_name LIKE ? AND leaf_category = TRUE", "%#{@product_to_sell.product.category}%"]).first.try(:category_id)

    respond_to do |format|
      if @product_to_sell.save
        format.html { redirect_to @product_to_sell, notice: 'Product to sell was successfully created.' }
        format.json { render :show, status: :created, location: @product_to_sell }
      else
        format.html { render :new }
        format.json { render json: @product_to_sell.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_to_sells/1
  # PATCH/PUT /product_to_sells/1.json
  def update
    respond_to do |format|
      if @product_to_sell.update(product_to_sell_params)
        format.html { redirect_to @product_to_sell, notice: 'Product to sell was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_to_sell }
      else
        format.html { render :edit }
        format.json { render json: @product_to_sell.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_to_sells/1
  # DELETE /product_to_sells/1.json
  def destroy
    @product_to_sell.destroy
    respond_to do |format|
      format.html { redirect_to product_to_sells_url, notice: 'Product to sell was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /product_to_sells/refresh
  # POST /product_to_sells/refresh.json
  def refresh
    ProductToSell.all.each_with_index do |p, i|
      lookup p.product.asin
    end
    redirect_to product_to_sells_path
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_product_to_sell
    @product_to_sell = ProductToSell.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_to_sell_params
    params.require(:product_to_sell).permit(:product_id, :category_id, :listed)
  end

  def remember_previous_page
    session[:previous_page] = request.env['HTTP_REFERER'] || product_to_sells_url
  end

  def list_to_ebay(api_call_name = "VerifyAddItem", start_price = nil)
    if @product_to_sell.category_id && @product_to_sell.listed
      @product = @product_to_sell.product

      @header = {
        "X-EBAY-API-DEV-NAME" => DEVID,
        "X-EBAY-API-APP-NAME" => APPID,
        "X-EBAY-API-CERT-NAME" => CERTID,
        "X-EBAY-API-CALL-NAME" => api_call_name,
        "X-EBAY-API-COMPATIBILITY-LEVEL" => API_COMPATIBILITY_LEVEL,
        "X-EBAY-API-SITEID" => EBAY_API_SITEID,
        "Content-Type" => "text/xml",
      }

      descriptions = Array.new
      descriptions << "Brand new #{@product.title}(#{@product.manufacturer})"
      descriptions << "Model:#{@product.model}" if @product.model
      descriptions << "Color:#{@product.color}" if @product.color
      descriptions << "Size:#{@product.size}" if @product.size
      descriptions << "Free international shipping from Japan"

      if start_price.blank?
        # start_price = (@product.price*0.95).round(0)
        start_price = @product.price.round(0)
      end
      condition_id = 1000
      listing_duration = "Days_5"
      listing_type = "Chinese"
      payment_methods = "PayPal"
      paypal_email = "crudo@hiroyukikondo.com"

      pictures = Array.new
      pictures << "<PictureURL>#{@product.image_url1}</PictureURL>" unless @product.image_url1.blank?
      pictures << "<PictureURL>#{@product.image_url2}</PictureURL>" unless @product.image_url2.blank?
      pictures << "<PictureURL>#{@product.image_url3}</PictureURL>" unless @product.image_url3.blank?
      pictures << "<PictureURL>#{@product.image_url4}</PictureURL>" unless @product.image_url4.blank?
      pictures << "<PictureURL>#{@product.image_url5}</PictureURL>" unless @product.image_url5.blank?

      xml = "
<?xml version='1.0' encoding='utf-8'?>
<#{api_call_name}Request xmlns='urn:ebay:apis:eBLBaseComponents'>
  <RequesterCredentials>
    <eBayAuthToken>#{TOKEN}</eBayAuthToken>
  </RequesterCredentials>
  <ErrorLanguage>en_US</ErrorLanguage>
  <WarningLevel>High</WarningLevel>
  <Item>
    <Title>#{@product.title} [#{@product.asin}]</Title>
    <Description>#{descriptions.join(', ')}</Description>
    <PrimaryCategory>
      <CategoryID>#{@product_to_sell.category_id}</CategoryID>
    </PrimaryCategory>
    <StartPrice>#{start_price}</StartPrice>
    <CategoryMappingAllowed>true</CategoryMappingAllowed>
    <ConditionID>#{condition_id}</ConditionID>
    <Country>JP</Country>
    <Currency>USD</Currency>
    <DispatchTimeMax>3</DispatchTimeMax>
    <ListingDuration>#{listing_duration}</ListingDuration>
    <ListingType>#{listing_type}</ListingType>
    <PaymentMethods>#{payment_methods}</PaymentMethods>
    <PayPalEmailAddress>#{paypal_email}</PayPalEmailAddress>
    <PictureDetails>
      #{pictures.join("
")}
    </PictureDetails>
    <Location>Fukuoka</Location>
    <Quantity>1</Quantity>
    <ReturnPolicy>
      <ReturnsAcceptedOption>#{@@return_accespted_option}</ReturnsAcceptedOption>
      <RefundOption>#{@@refund_option}</RefundOption>
      <ReturnsWithinOption>#{@@returns_within_option}</ReturnsWithinOption>
      <Description>#{@@refund_description}</Description>
      <ShippingCostPaidByOption>Buyer</ShippingCostPaidByOption>
    </ReturnPolicy>
    <ShippingDetails>
      <ShippingType>Flat</ShippingType>
      <ShippingServiceOptions>
        <ShippingServicePriority>1</ShippingServicePriority>
        <ShippingService>USPSStandardPost</ShippingService>
        <ShippingServiceCost>0</ShippingServiceCost>
      </ShippingServiceOptions>
    </ShippingDetails>
    <Site>US</Site>
  </Item>
</#{api_call_name}Request>
"

      puts "XML: #{xml}"

      response = Typhoeus::Request.post(URL, :body => xml, :headers => @header )
      hash = Hash.from_xml(response.response_body)

      puts hash

      if api_call_name == "VerifyAddItem"
        fees = 0
        if hash["VerifyAddItemResponse"] && hash["VerifyAddItemResponse"]["Fees"] && hash["VerifyAddItemResponse"]["Fees"]["Fee"]
          fees = hash["VerifyAddItemResponse"]["Fees"]["Fee"].inject(0) {|sum, i| sum += i["Fee"].to_f; sum}
          # hash["VerifyAddItemResponse"]["Fees"]["Fee"].each do |fee|
          #   fees += fee["Fee"].to_f
          # end
        end
        puts "TOTAL FEE: $#{fees}"

        begin
          list_to_ebay("AddItem", params[:start_price]) if fees < 1

app/helpers/product_to_sells_helper.rb
module ProductToSellsHelper
end

app/views/product_to_sells/_form.html.haml
= form_for @product_to_sell do |f|
  - if @product_to_sell.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product_to_sell.errors.count, "error")} prohibited this product_to_sell from being saved:"
      %ul
        - @product_to_sell.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :product
    = @product_to_sell.product.title
  .field
    = f.label :categpry_id
    = f.text_field :category_id
  .field
    = f.label :start_price
    = text_field_tag :start_price, @start_price
  .field
    = f.label :listed
    = f.check_box :listed
    .actions
    = f.submit 'Save', :class => "btn btn-default"

app/views/product_to_sells/edit.html.haml
%h1 Editing product_to_sell

= render 'form'

- if length = @product_to_sell.product.title &&  @product_to_sell.product.title.index(" ")
  - if length > 80
    = link_to t("links.edit") + t("activerecord.models.product"), edit_product_path(@product_to_sell.product), target: "blank", class: "btn btn-danger"
= link_to 'Show', @product_to_sell, :class => "btn btn-default"
= link_to 'Back', product_to_sells_path, :class => "btn btn-default"

app/views/product_to_sells/index.html.haml
%h1 Listing Products to Sell

= form_tag("/product_to_sells", :method => :get) do
  .form-inline
    .field
      .float-left
        %div
          = label_tag :category
          = select_tag :category, options_for_select(@categories, :selected => params[:category]), :include_blank => true, :class => "form-control"
          .checkboxes
            - if params[:listed]
              = check_box_tag :listed, 1, :checked => true
            - else
              = check_box_tag :listed, 1
            = label_tag :listed
            - if params[:unlisted]
              = check_box_tag :unlisted, 1, :checked => true
            - else
              = check_box_tag :unlisted, 1
            = label_tag :unlisted
            - if params[:sales_rank]
              = check_box_tag :sales_rank, 1, :checked => true
            - else
              = check_box_tag :sales_rank, 1
            = label_tag :sales_rank
            = check_box_tag :refresh, 1
            = label_tag :refresh
            - if params[:manufacture]
              = hidden_tag :manufacturer, params[:manufacturer]
      .float-left
        = label_tag :low_price
        = text_field_tag :low_price, params[:low_price], class: "form-control"
        = label_tag :high_price
        = text_field_tag :high_price, params[:high_price], class: "form-control"
      .float-left
        = submit_tag "Search", :class => "btn btn-default"
        = link_to 'New Product', new_product_path, :class => "btn btn-default"
        = link_to 'Refresh', refresh_product_to_sells_path, :class => "btn btn-default"
      .clear
      .float-right= paginate @product_to_sells

%table.table.table-condensed.table-striped.products
  %tr
    %th Category
    %th Manufacturer
    %th Product
    %th Images
    %th Price
    %th
      Costs:
      Supply
      %br
      Shipping
      %br
      Ebay
      %br
      PayPal
    %th.col-sm-1 Profit
    %th.col-sm-1 Ebay
    %th Category ID
    %th Listed
    %th
    %th

  - @product_to_sells.each do |pts|
    %tr
      %td= pts.product.category
      %td
        - if pts.product.manufacturer
          = link_to pts.product.manufacturer, "/product_to_sells/manufacturers/#{pts.product.manufacturer}"
      %td= link_to pts.product.title, product_path(pts.product)
      %td
        = link_to image_tag(pts.product.image_url1.sub(/.jpg$/, "._SL75_.jpg")), pts.product.image_url1, "data-lightbox" => pts.product.image_url1 rescue nil
        = link_to image_tag(pts.product.image_url2.sub(/.jpg$/, "._SL75_.jpg")), pts.product.image_url2, "data-lightbox" => pts.product.image_url2 rescue nil
        = link_to image_tag(pts.product.image_url3.sub(/.jpg$/, "._SL75_.jpg")), pts.product.image_url3, "data-lightbox" => pts.product.image_url3 rescue nil
        = link_to image_tag(pts.product.image_url4.sub(/.jpg$/, "._SL75_.jpg")), pts.product.image_url4, "data-lightbox" => pts.product.image_url4 rescue nil
        = link_to image_tag(pts.product.image_url5.sub(/.jpg$/, "._SL75_.jpg")), pts.product.image_url5, "data-lightbox" => pts.product.image_url5 rescue nil
      %td
        - if pts.product.price
          - case pts.product.currency
          - when "USD"
            %p= link_to number_to_currency(pts.product.price, :locale => :en), pts.product.url, target: :blank
            %p= "#{number_to_currency pts.product.price * @exchange_rate}(@#{@exchange_rate})"
      %td
        - if pts.product.url_jp
          %p= link_to number_to_currency(pts.product.cost), "#{URI.decode(pts.product.url_jp).sub(/\?.+$/, '')}#{AMAZON_ASSOCIATE_JP}", target: :blank
        - else
          .center
            %p -
        %p
          = number_to_currency pts.product.shipping_cost
          %br
          - if pts.product.weight && pts.product.weight > 220
            = surround "(", "kg)" do
              = (pts.product.weight.to_f / 100 * 0.454).round(2)
          - elsif pts.product.weight
            = surround "(", "g)" do
              = (pts.product.weight.to_f * 4.54).round(0)
          - else
            %p.center -
        - if pts.product.price
          %p= number_to_currency pts.product.price * 0.1 * @exchange_rate
        - else
          %p.center -
        - if pts.product.price
          %p= number_to_currency (pts.product.price * 0.039 + 0.3) * @exchange_rate
        - else
          %p.center -
      %td
        - if pts.product.price && pts.product.cost
          %p
            [amazon]
            %br
            - if @profit_hash[pts.product_id]/pts.product.cost.to_f > 0.2
              %span.green
                = number_to_currency @profit_hash[pts.product_id]
                %br
                = "(#{(100*@profit_hash[pts.product_id]/pts.product.cost).round(0)}%)"
            - elsif @profit_hash[pts.product_id] < 0
              %span.red
                = number_to_currency @profit_hash[pts.product_id]
            - else
              = number_to_currency @profit_hash[pts.product_id]
              %br
              = "(#{(100*@profit_hash[pts.product_id]/pts.product.cost).round(0)}%)"
        - unless @sold_items[pts.product.id].blank?
          %p
            [ebay]
            %br
            - if pts.product.cost
              - ebay_profit = ((@sold_items[pts.product.id].inject{ |sum, el| sum + el }.to_f / @sold_items[pts.product.id].size).round(2) * (1 - 0.1 - 0.039) - 0.3)*@exchange_rate - pts.product.cost - pts.product.shipping_cost
              - if ebay_profit/pts.product.cost.to_f > 0.2
                %span.green
                  = number_to_currency ebay_profit
                  %br
                  = "(#{(100*ebay_profit/pts.product.cost).round(0)}%)"
              - elsif ebay_profit < 0
                %span.red
                  = number_to_currency ebay_profit
              - else
                = number_to_currency ebay_profit
                %br
                = "(#{(100*ebay_profit/pts.product.cost).round(0)}%)"

          -# - if @profit_hash[pts.product_id]/(pts.product.price*@exchange_rate.to_f) > 0.1
          -#   %span.green
          -# - elsif @profit_hash[pts.product_id] < 0
          -#   %span.red
          -# = number_to_currency @profit_hash[pts.product_id]
      %td
        - unless @ebay_items[pts.product.id].blank?
          %p
            = t("views.product.all_count")
            = number_with_delimiter @ebay_items[pts.product.id].count
            - if @ebay_items[pts.product.id].count > 0
              %br
              = t("views.product.sold_count")
              = number_with_delimiter @sold_items[pts.product.id].count
              - if @sold_items[pts.product.id].count > 0
                %p
                  = t("views.product.highest")
                  %br
                  = "#{@locale} #{@sold_items[pts.product.id].last}"
                  %br
                  = t("views.product.average")
                  %br
                  = "#{@locale} #{@averages[pts.product.id]}"
                  -# = "#{@locale} #{(@sold_items[pts.product.id].inject{ |sum, el| sum + el }.to_f / @sold_items[pts.product.id].size).round(1)}"
        = link_to "More items", "http://www.ebay.com/sch/i.html?_nkw=#{URI.escape(pts.product.title)}&LH_Complete=1&LH_Sold=1&rt=nc", target: "blank"
      %td= pts.category_id
      %td
        - if pts.listed
          %span.btn.btn-success Listed
      %td
        = link_to 'Show', product_to_sell_path(pts), class: "btn btn-default"
        = link_to 'Edit', edit_product_to_sell_path(pts), class: "btn btn-default"
        = link_to 'Sold', "#{new_order_path}/#{pts.product_id}", class: "btn btn-info"
        = link_to 'Destroy', pts, :method => :delete, :data => { :confirm => 'Are you sure?' }, class: "btn btn-danger"

.float-right= paginate @product_to_sells

-# = link_to 'New Product to sell', new_product_to_sell_path, class: "btn btn-default"

app/views/product_to_sells/new.html.haml
%h1 New product_to_sell

= render 'form'

= link_to 'Back', product_to_sells_path

app/views/product_to_sells/show.html.haml
%table.table.table-bordered
  %tr
    %th
      %strong Ebay Category ID
    %td= @product_to_sell.category_id
  %tr
    %th
      %strong Asin
    %td
      = @product_to_sell.product.asin
      [
      = link_to "US", @product_to_sell.product.url, target: :blank
      |
      = link_to "JP", "#{URI.decode(@product_to_sell.product.url_jp).sub(/\?.+$/, '')}#{AMAZON_ASSOCIATE_JP}", target: :blank rescue nil
      ]
  %tr
    %th
      %strong Category
    %td= @product_to_sell.product.category
  %tr
    %th
      %strong Manufacturer
    %td= @product_to_sell.product.manufacturer
  %tr
    %th
      %strong Model
    %td= @product_to_sell.product.model
  %tr
    %th
      %strong Title
    %td
      = "#{@product_to_sell.product.title}(#{@product_to_sell.product.title.size})"
      = link_to t("links.edit"), edit_product_path(@product_to_sell.product)
  %tr
    %th
      %strong Color
    %td= @product_to_sell.product.color
  %tr
    %th
      %strong Size
    %td= @product_to_sell.product.size
  %tr
    %th
      %strong Weight
    %td
      = @product_to_sell.product.weight
      - if @product_to_sell.product.weight > 220
        = surround "(", "kg)" do
          = (@product_to_sell.product.weight.to_f / 100 * 0.454).round(2)
      - else
        = surround "(", "g)" do
          = (@product_to_sell.product.weight.to_f * 4.54).round(0)
  %tr
    %th
      %strong Features
    %td= @product_to_sell.product.features
  %tr
    %th
      %strong Sales rank
    %td= number_with_delimiter @product_to_sell.product.sales_rank
  %tr
    %th
      %strong Images
    %td
      = link_to image_tag(@product_to_sell.product.image_url1.sub(/.jpg$/, "._SL160_.jpg")), @product_to_sell.product.image_url1, "data-lightbox" => @product_to_sell.product.image_url1 rescue nil
      = link_to image_tag(@product_to_sell.product.image_url2.sub(/.jpg$/, "._SL160_.jpg")), @product_to_sell.product.image_url2, "data-lightbox" => @product_to_sell.product.image_url2 rescue nil
      = link_to image_tag(@product_to_sell.product.image_url3.sub(/.jpg$/, "._SL160_.jpg")), @product_to_sell.product.image_url3, "data-lightbox" => @product_to_sell.product.image_url3 rescue nil
      = link_to image_tag(@product_to_sell.product.image_url4.sub(/.jpg$/, "._SL160_.jpg")), @product_to_sell.product.image_url4, "data-lightbox" => @product_to_sell.product.image_url4 rescue nil
      = link_to image_tag(@product_to_sell.product.image_url5.sub(/.jpg$/, "._SL160_.jpg")), @product_to_sell.product.image_url5, "data-lightbox" => @product_to_sell.product.image_url5 rescue nil
  %tr
    %th
      %strong Price
    %td
      - if @product_to_sell.product.price
        - case @product_to_sell.product.currency
        - when "USD"
          = link_to number_to_currency(@product_to_sell.product.price, :locale => :en), @product_to_sell.product.url, target: :blank
  %tr
    %th
      %strong Cost
    %td= link_to number_to_currency(@product_to_sell.product.cost), "#{@product_to_sell.product.url_jp.sub(/\?.+$/, '')}#{AMAZON_ASSOCIATE_JP}", target: :blank if @product_to_sell.product.cost
  %tr
    %th
      %strong Shipping cost
    %td= number_to_currency @product_to_sell.product.shipping_cost
  %tr
    %th
      %strong Profit
    %td
      - if @product_to_sell.product.price && @product_to_sell.product.cost
        %p
          [amazon]
          %br
          - if @profit/@product_to_sell.product.cost.to_f > 0.1
            %span.green
              = number_to_currency @profit
              %br
              = "(#{(100*@profit/@product_to_sell.product.cost).round(0)}%)"
          - elsif @profit < 0
            %span.red
              = number_to_currency @profit
          - else
            = number_to_currency @profit
            %br
            = "(#{(100*@profit/@product_to_sell.product.cost).round(0)}%)"
      - unless @sold_items.blank?
        %p
          [ebay]
          %br
          - if @product_to_sell.product.cost
            - if @ebay_profit/@product_to_sell.product.cost.to_f > 0.2
              %span.green
                = number_to_currency @ebay_profit
                %br
                = "(#{(100*@ebay_profit/@product_to_sell.product.cost).round(0)}%)"
            - elsif @ebay_profit < 0
              %span.red
                = number_to_currency @ebay_profit
            - else
              = number_to_currency @ebay_profit
              %br
              = "(#{(100*@ebay_profit/@product_to_sell.product.cost).round(0)}%)"
  %tr
    %th
      %p
        %strong Ebay Items
      .left
        = t("views.product.all_count")
        = @ebay_items.count
        %br
        = t("views.product.sold_count")
        = number_with_delimiter @sold_items.count
        - if @average
          %br
          = t("views.product.average")
          = "#{@locale} #{number_with_delimiter @average}"
    %td
      %ul
        - @ebay_items.each do |item|
          %li
            = link_to item.title, ebay_item_path(item)
            - if item.selling_state == "EndedWithSales"
              %b.green= item.selling_state
            - elsif item.selling_state == "EndedWithoutSales"
              %span.red= item.selling_state
            = link_to "(#{item.current_price_currency_id} #{item.current_price_value}@#{item.end_time.strftime('%Y/%m/%d')})", item.view_item_url
      %p.right= link_to "More on Advanced Search at ebay.com", "http://www.ebay.com/sch/i.html?_nkw=#{URI.escape(@product_to_sell.product.title)}"
= link_to 'Edit', edit_product_to_sell_path(@product_to_sell), :class => "btn btn-default"
= link_to 'Refresh', "#{refresh_products_path}/#{@product_to_sell.product.id}", :class => "btn btn-default"
= link_to 'Destroy', @product_to_sell, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger"
= link_to 'Back', session[:previous_page], :class => "btn btn-default"